feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression: # 开启Feign请求响应压缩
    request:
      enabled: true
      # 配置压缩文档类型及最小压缩的文档大小
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true
logging:
  level:
    com.alibaba.nacos.client.naming: warn
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: NOT_NULL  # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      # 逻辑删除配置
      logic-delete-value: true
      logic-not-delete-value: false
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false  # 切换实例的重试
    sentinel:
      eager: true
      transport:
        dashboard: ${zlt.sentinel.dashboard}
  datasource:
    # 连接池配置(通常来说，只需要修改initialSize、minIdle、maxActive
    druid:
      filters: stat,wall
      initial-size: 10
      max-active: 500
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000 # 配置获取连接等待超时的时间
      min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-idle: 10
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # StatViewServlet配置
      stat-view-servlet:
        # 展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true # 是否启用StatViewServlet默认值true
        login-password: admin
        login-username: admin
        reset-enable: true  # 允许清空统计数据
        # 根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validation-query: SELECT 'x'
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true # 是否启用StatFilter默认值true
        exclusions: '"*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"'
        profile-enable: true
        session-stat-enable: false
        session-stat-max-count: 1000
        url-pattern: /*
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
