spring:
  elasticsearch:
    rest:
      uris: ${zlt.elasticsearch.uris}
      username: ${zlt.elasticsearch.username}
      password: ${zlt.elasticsearch.password}

zlt:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*